name: medi_cal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  cloud_firestore: 4.8.0
  cloud_firestore_platform_interface: 5.15.0
  cloud_firestore_web: 3.6.0
  cloud_functions: 4.3.2
  cloud_functions_platform_interface: 5.4.2
  cloud_functions_web: 4.5.2
  csv: 5.0.1
  dropdown_button2: 2.0.0
  easy_debounce: 2.0.1
  equatable: 2.0.5
  firebase_analytics: 10.4.2
  firebase_analytics_platform_interface: 3.6.2
  firebase_analytics_web: 0.5.4+2
  firebase_app_check: 0.1.4+2
  firebase_app_check_platform_interface: 0.0.8+2
  firebase_app_check_web: 0.0.10+2
  firebase_auth: 4.6.2
  firebase_auth_platform_interface: 6.15.2
  firebase_auth_web: 5.5.2
  firebase_core: 2.13.1
  firebase_core_platform_interface: 4.8.0
  firebase_core_web: 2.5.0
  firebase_messaging: 14.6.2
  firebase_messaging_platform_interface: 4.5.2
  firebase_messaging_web: 3.5.2
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_secure_storage: 8.0.0
  flutter_svg: 2.0.4
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 4.0.3
  google_sign_in: 6.0.2
  google_sign_in_android: 6.1.8
  google_sign_in_ios: 5.6.1
  google_sign_in_platform_interface: 2.4.0
  google_sign_in_web: 0.11.0+2
  intl: 0.18.0
  json_path: 0.6.2
  lottie: 1.2.1
  mime_type: 1.0.0
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  plugin_platform_interface: 2.1.3
  provider: 6.0.4
  rxdart: 0.27.7
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sqflite: 2.2.6
  stream_transform: 2.1.0
  synchronized: 3.1.0
  table_calendar: 3.0.9
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: 0.12.0

  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  fonts:
    - family: 'Aristotelica'
      fonts:
        - asset: assets/fonts/AristotelicaProText-DemiBold.ttf
          weight: 600
        - asset: assets/fonts/aristotelica-text-trial-demibold.ttf
          weight: 700
    - family: 'Code Pro'
      fonts:
        - asset: assets/fonts/Code_Pro_Light.otf
          weight: 300
        - asset: assets/fonts/Code_Pro_Light_LC.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Code_Pro.otf
        - asset: assets/fonts/Code_Pro_LC.otf
          style: italic
        - asset: assets/fonts/Code_Pro_Bold.otf
          weight: 700
        - asset: assets/fonts/Code_Pro_Bold_LC.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Code_Pro_Black.otf
          weight: 900
        - asset: assets/fonts/Code_Pro_Black_LC.otf
          weight: 900
          style: italic
    - family: 'Codec Pro Warm'
      fonts:
        - asset: assets/fonts/Codec-Warm-Thin-trial.ttf
          weight: 100
        - asset: assets/fonts/Codec-Warm-Thin-Italic-trial.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Codec-Warm-ExtraLight-trial.ttf
          weight: 200
        - asset: assets/fonts/Codec-Warm-ExtraLight-Italic-trial.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Codec-Warm-Light-trial.ttf
          weight: 300
        - asset: assets/fonts/Codec-Warm-Light-Italic-trial.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Codec-Warm-Regular-trial.ttf
        - asset: assets/fonts/Codec-Warm-Regular-Italic-trial.ttf
          style: italic
        - asset: assets/fonts/Codec-Warm-News-trial.ttf
          weight: 500
        - asset: assets/fonts/Codec-Warm-News-Italic-trial.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Codec-Warm-Heavy-trial.ttf
          weight: 600
        - asset: assets/fonts/Codec-Warm-Heavy-Italic-trial.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Codec-Warm-Bold-trial.ttf
          weight: 700
        - asset: assets/fonts/Codec-Warm-Bold-Italic-trial.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Codec-Warm-ExtraBold-trial.ttf
          weight: 800
        - asset: assets/fonts/Codec-Warm-ExtraBold-Italic-trial.ttf
          weight: 800
          style: italic
    - family: 'Codec Pro Cold'
      fonts:
        - asset: assets/fonts/Codec-Cold-Thin-trial.ttf
          weight: 100
        - asset: assets/fonts/Codec-Cold-Thin-Italic-trial.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Codec-Cold-Extralight-trial.ttf
          weight: 200
        - asset: assets/fonts/Codec-Cold-Extralight-Italic-trial.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Codec-Cold-Light-trial.ttf
          weight: 300
        - asset: assets/fonts/Codec-Cold-Light-Italic-trial.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Codec-Cold-Regular-trial.ttf
        - asset: assets/fonts/Codec-Cold-Regular-Italic-trial.ttf
          style: italic
        - asset: assets/fonts/Codec-Cold-News-trial.ttf
          weight: 500
        - asset: assets/fonts/Codec-Cold-News-Italic-trial.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Codec-Cold-Heavy-trial.ttf
          weight: 600
        - asset: assets/fonts/Codec-Cold-Heavy-Italic-trial.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Codec-Cold-Bold-trial.ttf
          weight: 700
        - asset: assets/fonts/Codec-Cold-Bold-Italic-trial.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Codec-Cold-ExtraBold-trial.ttf
          weight: 800
        - asset: assets/fonts/Codec-Cold-ExtraBold-Italic-trial.ttf
          weight: 800
          style: italic


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
